# Generated by Django 4.0.5 on 2023-07-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userform',
            fields=[
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('Designation', models.CharField(max_length=100)),
                ('DateofJoinning', models.DateField()),
                ('Biometricid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('permission', models.IntegerField(default=0)),
            ],
        ),
    ]
