# Generated by Django 4.0.5 on 2023-07-01 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
