# Generated by Django 4.0.5 on 2023-07-06 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obeapp', '0002_remove_user_password_remove_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Coursenam', models.CharField(max_length=100)),
                ('Coursecode', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Regulation', models.CharField(max_length=100)),
                ('startyear', models.IntegerField()),
                ('endyear', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Userform',
            fields=[
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('Designation', models.CharField(max_length=100)),
                ('DateofJoinning', models.DateField()),
                ('Biometricid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
