# Generated by Django 4.0.5 on 2023-07-16 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obeapp', '0003_courses_regulation_userform_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
