# Generated by Django 4.2 on 2023-07-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obeapp', '0004_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='co_pso_Matrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cos', models.CharField(default='', max_length=10)),
                ('po1', models.CharField(default='', max_length=10)),
                ('po2', models.CharField(default='', max_length=10)),
                ('po3', models.CharField(default='', max_length=10)),
                ('po4', models.CharField(default='', max_length=10)),
                ('po5', models.CharField(default='', max_length=10)),
                ('po6', models.CharField(default='', max_length=10)),
                ('po7', models.CharField(default='', max_length=10)),
                ('po8', models.CharField(default='', max_length=10)),
                ('po9', models.CharField(default='', max_length=10)),
                ('po10', models.CharField(default='', max_length=10)),
                ('po11', models.CharField(default='', max_length=10)),
                ('po12', models.CharField(default='', max_length=10)),
                ('pso1', models.CharField(default='', max_length=10)),
                ('pso2', models.CharField(default='', max_length=10)),
                ('course_code', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='course_end_survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(default='1', max_length=5)),
                ('cos', models.CharField(default='', max_length=5)),
                ('question', models.CharField(default='', max_length=100)),
                ('course_code', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='courseoutcomes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co', models.CharField(default='1', max_length=5)),
                ('courseoutcome', models.CharField(max_length=100)),
                ('knowledge_level', models.CharField(default='K1', max_length=5)),
                ('course_code', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='details_of_instructors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(default='1', max_length=5)),
                ('name', models.CharField(default='', max_length=100)),
                ('designation', models.CharField(default='', max_length=100)),
                ('year', models.CharField(default='', max_length=20)),
                ('section', models.CharField(default='', max_length=20)),
                ('contactno', models.CharField(default='', max_length=30)),
                ('email', models.CharField(default='', max_length=50)),
                ('course_code', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='lectureplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(default='1', max_length=5)),
                ('course_outcome', models.CharField(default='CO1', max_length=10)),
                ('ilo', models.CharField(default='', max_length=100)),
                ('knowledgelevel', models.CharField(default='', max_length=5)),
                ('noof_hours', models.CharField(default='', max_length=5)),
                ('pedagogy', models.CharField(default='', max_length=50)),
                ('teachingaids', models.CharField(default='', max_length=10)),
                ('course_code', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='lessonplanBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=20)),
                ('academicyear', models.CharField(max_length=20)),
                ('programme', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=10)),
                ('name_of_the_course', models.CharField(max_length=70)),
                ('course_code', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='referencebooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(default='1', max_length=5)),
                ('rfbook_details', models.CharField(max_length=200)),
                ('course_code', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='targetproficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co', models.CharField(default='', max_length=15)),
                ('tpl', models.CharField(default='', max_length=15)),
                ('l3', models.CharField(default='', max_length=15)),
                ('l2', models.CharField(default='', max_length=15)),
                ('l1', models.CharField(default='', max_length=15)),
                ('course_code', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(default='sushma kurella', max_length=80)),
                ('passwd', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='textbooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(default=1, max_length=5)),
                ('textbook_details', models.CharField(max_length=200)),
                ('course_code', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Regulation',
        ),
        migrations.AddField(
            model_name='userform',
            name='permission',
            field=models.IntegerField(default=0),
        ),
    ]
