# Generated by Django 4.2 on 2023-07-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obeapp', '0005_co_pso_matrix_course_end_survey_courseoutcomes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sno', models.IntegerField()),
                ('Coursenam', models.CharField(max_length=100)),
                ('Coursecode', models.CharField(max_length=100)),
                ('Regulation', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=50)),
                ('semister', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sno', models.IntegerField()),
                ('Regulation', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=50)),
            ],
        ),
    ]
